services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    network_mode: "host"
    ports:
      - "8080:8080" #UI
      - "50000:50000" # agent connections (optional but common)
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped

volumes:
  jenkins_home:

